
services:
  - type: web
    name: mafia-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python mafia.py
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
      - key: ROOM_TTL_SECONDS
        value: 3600  # Changed from 900 to 3600 (1 hour)
